version: '3.8'
services:
  webapp:
    image: webapi
    container_name: webapiapp
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 8080:8080
    expose:
      - 8080
    # environment:
      # - ASPNETCORE_ENVIRONMENT=Production
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_USER=postgres
      # - DB_PASSWORD=admin42!
      # - DB_NAME=meddatadb

  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin42!
      POSTGRES_DB: meddatadb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db_data:
