version: '3.8'
services:
  webapp:
    image: webapi
    container_name: webapiapp
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./keys:/app/keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_CONNECTION=redis:6379 # Redis connection string

  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin42!
      POSTGRES_DB: meddatadb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis:alpine
    container_name: redisdb
    ports:
      - "6379:6379"
    expose:
      - 6379

volumes:
  db_data:
